use_frameworks!

target 'Keystore_Example' do
  pod 'Keystore', :path => '../'

  target 'Keystore_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
